contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #scdnalr channel"
    url: https://nfcore.slack.com/channels/scdnalr
    about: Discussion about the nf-core/scdnalr pipeline
